Feature/create board
migueliriano/checkers pull request #2
Opened 2017-04-21 19:34 UTC by edFortune

2017-04-21 20:11 UTC, migueliriano requested changes
Here some feedbacks

2017-04-21 20:11 UTC, migueliriano commented on index.html
> +</html>
Please add empty line in the end of the file.

the reason is: 

*lines not ending in a newline character aren't considered actual lines. That's why some programs have problems processing the last line of a file if it isn't newline terminated.*

2017-04-21 20:11 UTC, migueliriano commented on index.html
> +		<script type="text/javascript" src="scripts.js"></script>
Please can we be more specific with the name of the scripts file ? Maybe we can call this **checkers_main.js**

2017-04-21 20:11 UTC, migueliriano commented on index.html
> +		<link rel="stylesheet" href="style.css">
Please can we be more specific with the name of the css file ? Maybe we can call this checker_style.css

2017-04-21 20:11 UTC, migueliriano commented on scripts.js
> +
Please add empty line in the end of the file.

2017-04-21 20:11 UTC, migueliriano commented on scripts.js
> +					bloc.style.cssText = 'margin: 0%; width:50px; height:50px; background-color:#8B4500; display: table-cell;';
Can we add this style on the css file as a **Class** ? 
**i.e.:**

```css
.white-box-stile{
   margin: 0%;
   width:50px;
   height:50px;
   background-color:#8B4500;
   display: table-cell;
}
```
the that way we can only add the class name here and not repeat the style.

2017-04-21 20:11 UTC, migueliriano commented on scripts.js
> +}
we can use two`for` to populated the 3 rows the same for the **black pieces** and **white pieces**.

**i.e:**
```js
for (var row= 0; row < 3 ; row++ ){
    for (var box = 0; box < 8; box ++){
       //logic here
   }
}
```

2017-04-21 20:11 UTC, migueliriano commented on scripts.js
> +var l = 0;
can you be more descriptive with the name of the variable please ?

2017-04-21 20:11 UTC, migueliriano commented on scripts.js
> +var k = 0;
can you be more descriptive with the name of the variable please ?

2017-04-23 14:20 UTC, edFortune commented
@migueliriano  Some changes have been made to the code. Maybe you can get a look at them.

2017-04-24 13:35 UTC, migueliriano requested changes
Please can you add this logic on an javascript function call  `createCheckersBoard()`?

2017-04-24 13:35 UTC, migueliriano commented on checkerScripts.js
> +	if(rowChangeColor==0){rowChangeColor = 1;}else{rowChangeColor=0;}
You can do this `shorthand`
```Javascript
var rowChangeColor = (rowChangeColor === 0) ? 1 : 0;
```

2017-04-24 13:35 UTC, migueliriano commented on checkerScripts.js
> +				pieceWhite.id = 'white-piece';
Please use `CLASS` instated of `ID`.

2017-04-24 13:35 UTC, migueliriano commented on checkerStyle.css
> +#white-box{
Please use `CLASS` instated of `ID`
example: `.white-box`

2017-04-24 13:37 UTC, migueliriano commented
@edFortune I left some comments :)

2017-04-24 14:35 UTC, migueliriano commented
@edFortune  can you create a function call createCheckersBoard and put all the logic there ?

2017-04-24 16:39 UTC, migueliriano approved these changes

2017-04-24 16:40 UTC, merged